import { readdirSync, writeFileSync, statSync } from 'fs';
import { join, relative, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const testImagesDir = join(__dirname, '..', 'demo', 'public', 'test-images');
const outputPath = join(__dirname, '..', 'demo', 'src', 'lib', 'test-manifest.ts');

interface TestImage {
  path: string;
  filename: string;
  category: string;
}

const images: TestImage[] = [];

const categories = readdirSync(testImagesDir).filter((name) => {
  return statSync(join(testImagesDir, name)).isDirectory();
});

for (const category of categories.sort()) {
  const dir = join(testImagesDir, category);
  const files = readdirSync(dir)
    .filter((f) => /\.(jpe?g|png|webp)$/i.test(f))
    .sort((a, b) => {
      const numA = parseInt(a.match(/\d+/)?.[0] ?? '0');
      const numB = parseInt(b.match(/\d+/)?.[0] ?? '0');
      return numA - numB;
    });

  for (const file of files) {
    images.push({
      path: `/test-images/${category}/${file}`,
      filename: file,
      category,
    });
  }
}

const output = `// Auto-generated by scripts/gen-test-manifest.ts — do not edit manually
// Run: npx tsx scripts/gen-test-manifest.ts

export interface TestImage {
  path: string;
  filename: string;
  category: string;
}

export const testImages: TestImage[] = ${JSON.stringify(images, null, 2)};

export const testCategories = [...new Set(testImages.map((i) => i.category))];
`;

writeFileSync(outputPath, output, 'utf-8');
console.log(`Generated ${images.length} test images in ${categories.length} categories → ${relative(process.cwd(), outputPath)}`);
