// Auto-generated by scripts/gen-test-manifest.ts — do not edit manually
// Run: npx tsx scripts/gen-test-manifest.ts

export interface GroundTruth {
  /** Ordered card corners: [TL, TR, BR, BL] in original image pixels (1920x1080). */
  corners: [
    { x: number; y: number },
    { x: number; y: number },
    { x: number; y: number },
    { x: number; y: number },
  ];
}

export interface TestImage {
  path: string;
  filename: string;
  category: string;
  groundTruth?: GroundTruth;
}

export const testImages: TestImage[] = [
  {
    "path": "/test-images/paper-bg/Photo-1.jpeg",
    "filename": "Photo-1.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-2.jpeg",
    "filename": "Photo-2.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-3.jpeg",
    "filename": "Photo-3.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-4.jpeg",
    "filename": "Photo-4.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-5.jpeg",
    "filename": "Photo-5.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-6.jpeg",
    "filename": "Photo-6.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-7.jpeg",
    "filename": "Photo-7.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-8.jpeg",
    "filename": "Photo-8.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-9.jpeg",
    "filename": "Photo-9.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-10.jpeg",
    "filename": "Photo-10.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-11.jpeg",
    "filename": "Photo-11.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-12.jpeg",
    "filename": "Photo-12.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-13.jpeg",
    "filename": "Photo-13.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-14.jpeg",
    "filename": "Photo-14.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-15.jpeg",
    "filename": "Photo-15.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-16.jpeg",
    "filename": "Photo-16.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-17.jpeg",
    "filename": "Photo-17.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-18.jpeg",
    "filename": "Photo-18.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-19.jpeg",
    "filename": "Photo-19.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-20.jpeg",
    "filename": "Photo-20.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-21.jpeg",
    "filename": "Photo-21.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-22.jpeg",
    "filename": "Photo-22.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-23.jpeg",
    "filename": "Photo-23.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/paper-bg/Photo-24.jpeg",
    "filename": "Photo-24.jpeg",
    "category": "paper-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-25.jpeg",
    "filename": "Photo-25.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-26.jpeg",
    "filename": "Photo-26.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-27.jpeg",
    "filename": "Photo-27.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-28.jpeg",
    "filename": "Photo-28.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-29.jpeg",
    "filename": "Photo-29.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-30.jpeg",
    "filename": "Photo-30.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-31.jpeg",
    "filename": "Photo-31.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-32.jpeg",
    "filename": "Photo-32.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-33.jpeg",
    "filename": "Photo-33.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-34.jpeg",
    "filename": "Photo-34.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-35.jpeg",
    "filename": "Photo-35.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-36.jpeg",
    "filename": "Photo-36.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-37.jpeg",
    "filename": "Photo-37.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-38.jpeg",
    "filename": "Photo-38.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-39.jpeg",
    "filename": "Photo-39.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-40.jpeg",
    "filename": "Photo-40.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-41.jpeg",
    "filename": "Photo-41.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-42.jpeg",
    "filename": "Photo-42.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-43.jpeg",
    "filename": "Photo-43.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-44.jpeg",
    "filename": "Photo-44.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-45.jpeg",
    "filename": "Photo-45.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-46.jpeg",
    "filename": "Photo-46.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-47.jpeg",
    "filename": "Photo-47.jpeg",
    "category": "wood-bg"
  },
  {
    "path": "/test-images/wood-bg/Photo-48.jpeg",
    "filename": "Photo-48.jpeg",
    "category": "wood-bg"
  }
];

export const testCategories = [...new Set(testImages.map((i) => i.category))];

/** Compute mean corner distance (pixels) between detected and ground truth quads. */
export function computeAccuracy(
  detected: { x: number; y: number }[],
  truth: GroundTruth,
  scale: number = 1,
): { meanDist: number; maxDist: number; perCorner: number[] } {
  const perCorner: number[] = [];
  let sum = 0;
  let max = 0;
  for (let i = 0; i < 4; i++) {
    const dx = detected[i].x / scale - truth.corners[i].x;
    const dy = detected[i].y / scale - truth.corners[i].y;
    const dist = Math.sqrt(dx * dx + dy * dy);
    perCorner.push(dist);
    sum += dist;
    if (dist > max) max = dist;
  }
  return { meanDist: sum / 4, maxDist: max, perCorner };
}
